---
profiles:
  default:
    endpoints: default
    imageId: emi-fb0813f6
    instanceType: m2.4xlarge
  qa-cloud:
    endpoints: qa-cloud
    imageId:  emi-45C77519
    volumeSize: "10"
    instanceType: m2.2xlarge
  aws:
    endpoints: aws
    imageId: ami-c4072e81
    instanceType: t1.micro
    region: us-west-1
endpoints:
  default:
    ec2Endpoint: 'http://compute.cloud.home'
    iamEndpoint: 'http://euare.cloud.home'
  qa-cloud:
    ec2Endpoint: 'http://10.111.1.136:8773/services/compute/'
    iamEndpoint: 'http://10.111.1.136:8773/services/Euare/'
