name 'mesos-extras'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mesos-extras'
long_description 'Installs/Configures mesos-extras'
version '0.1.0'
depends 'mesos'
